### ISSUE TITLE
Collaborative Proposal with go-nv/goenv

### ISSUE THREAD

**Issue by ChronosMasterOfAllTime** [ankitcharolia/goenv#13]
@ankitcharolia  please see go-nv/goenv#342. I like the idea of a higher order language for a CLI tool. Especially one using golang and goreleaser. Please comment if interested in a collaborative effort for a more "official" V3 version.

**Comment by ankitcharolia** [comment]
@ChronosMasterOfAllTime I am currently working on another golang project. I will look into this bit later.
