### ISSUE TITLE
goenv --list-remotes should list versions in the reverse order

### ISSUE THREAD

**Issue by gl-yziquel** [ankitcharolia/goenv#24]
Hi.

I just got around to testing goenv.

I just typed `goenv --list-remote`.

The list starts at version 1.22rc1 and ends at version 1.

So you have to scroll up.

It would be a better user experience if you did not have to scroll up and thus if the list of versions started at 1 and ended at 1.22rc1.

Just my 2 cents after 1 minute of playing around with `goenv`.

**Comment by ankitcharolia** [comment]
@gl-yziquel will look into it. it should be easy. Thank you for raising the issue.
