### ISSUE TITLE
readme update?

### ISSUE THREAD

**Issue by scarrington76** [ankitcharolia/goenv#8]
looks like there is a version variable I am supposed to supply in the copied wget command. What is the current version?

<img width="1122" alt="Screen Shot 2023-08-09 at 9 14 23 AM" src="https://github.com/ankitcharolia/goenv/assets/50926634/be086580-fd24-40c2-bb25-2e78eae51eed">

**Comment by shaozi17** [comment]
You can find it on [Releases](https://github.com/ankitcharolia/goenv/releases), such as 1.1.3
![image](https://github.com/ankitcharolia/goenv/assets/22265868/65ad102d-e0c0-45e1-bfe3-dfdf8e9be203)

**Comment by ankitcharolia** [comment]
@scarrington76 you can always download the latest version like this: 
`wget -O - https://github.com/ankitcharolia/goenv/releases/latest/download/goenv-linux-amd64.tar.gz | tar -xz -C ~/.go`
